version: "2"
services:
  pvsdb:
    image: mongo
    networks:
      - pvsdbnetwork
    volumes:
      - pvs-mongo-volume:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=pvsdb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=pvs
    networks:
      - pvsdbnetwork
  pvsapi:
    build: ./pvs-api
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - pvsdb
    networks:
      - pvsdbnetwork
    environment:
      - FB_GROUP_ID=${FB_GROUP_ID}
      - FB_ACCESS_TOKEN=${FB_ACCESS_TOKEN}
volumes:
  pvs-mongo-volume:
networks:
  pvsdbnetwork:
    